### ISSUE TITLE
Not allowing certain registrations

### ISSUE THREAD

**Issue by jscottchapman** [associatedemployers/safely#31]
People who are registering for this Friday afternoon are getting a server error and it doesn't register them.  The error they are getting are originating from line 119 of https://github.com/associatedemployers/safely-api/blob/master/lib/models/registration/middleware/assign-seat.js

**Comment by James1x0** [comment]
@jscottchapman Need specific repro steps for this. Selected company, trainee, any class (1 or 2hr), selected 12-2 time block for friday - works, selected 2-4 time block for friday - works.
